name: ClusterFuzzLite continuous builds
on:
  push:
    branches:
      - main
permissions: read-all
jobs:
  Build:
   runs-on: ubuntu-latest
   concurrency:
     group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
     cancel-in-progress: true
   strategy:
     fail-fast: false
     matrix:
        sanitizer:
        - address
        - undefined # Add other sanitizers like 'memory' if needed, each as a separate item.
   steps:
   - name: Build Fuzzers (${{ matrix.sanitizer }})
     id: build
     uses: google/clusterfuzzlite/actions/build_fuzzers@v1
     with:
        language: rust
        sanitizer: ${{ matrix.sanitizer }}
        upload-build: true
